const D=window.FLIGHT_DATA;
const yearEl=document.querySelector('#yearFilter'),countryEl=document.querySelector('#countryFilter');
const years=[...new Set(D.annual.map(x=>x.year))].sort((a,b)=>a-b);
const countries=[...new Set(D.annual.map(x=>x.country))].sort((a,b)=>a.localeCompare(b,'zh-Hant'));
let selectedSummaryCountry=null,selectedAircraft=null;
years.forEach(y=>yearEl.insertAdjacentHTML('beforeend',`<option value="${y}">${y}</option>`));
countries.forEach(c=>countryEl.insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`));
const pad=n=>String(n).padStart(2,'0');
function dur(sec){if(sec==null||!Number.isFinite(Number(sec)))return'—';sec=Math.max(0,Math.round(Number(sec)));const d=Math.floor(sec/86400);sec%=86400;const h=Math.floor(sec/3600);sec%=3600;const m=Math.floor(sec/60),s=sec%60;return`${d}天 ${pad(h)}時${pad(m)}分${pad(s)}秒`;}
const dt=s=>s?s.replace('T',' '):'—';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const diff=(a,b)=>Math.max(0,(new Date(b)-new Date(a))/1000);
function baseVisits(){return D.visits.filter(x=>(yearEl.value==='all'||x.arrival.startsWith(yearEl.value))&&(countryEl.value==='all'||x.country===countryEl.value));}
function aggregateVisits(visits){const g=new Map();visits.forEach(v=>{if(!g.has(v.country))g.set(v.country,[]);g.get(v.country).push(v)});return[...g].map(([country,list])=>{list.sort((a,b)=>a.arrival.localeCompare(b.arrival));const total=list.reduce((s,v)=>s+(Number(v.durationSeconds)||0),0),gaps=[];for(let i=1;i<list.length;i++)gaps.push(diff(list[i-1].arrival,list[i].arrival));return{year:'all',country,visits:list.length,avg_interval_seconds:gaps.length?Math.round(gaps.reduce((a,b)=>a+b,0)/gaps.length):null,avg_stay_seconds:list.length?Math.round(total/list.length):0,total_stay_seconds:total};});}
function filteredAnnual(){if(yearEl.value==='all')return aggregateVisits(baseVisits());return D.annual.filter(x=>String(x.year)===yearEl.value&&(countryEl.value==='all'||x.country===countryEl.value));}
function filteredVisits(){return baseVisits().filter(x=>!selectedSummaryCountry||x.country===selectedSummaryCountry);}
function baseFlights(){return D.flights.filter(x=>(yearEl.value==='all'||x.date.startsWith(yearEl.value))&&(countryEl.value==='all'||x.fromCountry===countryEl.value||x.toCountry===countryEl.value));}
function filteredFlights(){return baseFlights().filter(x=>!selectedAircraft||x.aircraft===selectedAircraft);}
function flightSec(x){return Number.isFinite(Number(x.durationSeconds))?Number(x.durationSeconds):(x.departure&&x.arrival?diff(x.departure,x.arrival):0);}
function aircraftSummary(){const g=new Map();baseFlights().filter(x=>x.completed&&x.aircraft&&x.aircraft.trim()).forEach(f=>{if(!g.has(f.aircraft))g.set(f.aircraft,[]);g.get(f.aircraft).push(f)});return[...g].map(([aircraft,list])=>{list.sort((a,b)=>a.departure.localeCompare(b.departure));const total=list.reduce((s,f)=>s+flightSec(f),0),gaps=[];for(let i=1;i<list.length;i++)gaps.push(diff(list[i-1].departure,list[i].departure));return{aircraft,flights:list.length,avg_interval_seconds:gaps.length?Math.round(gaps.reduce((a,b)=>a+b,0)/gaps.length):null,avg_flight_seconds:Math.round(total/list.length),total_flight_seconds:total,years:[...new Set(list.map(f=>f.date.slice(0,4)))].sort().join('、')};}).sort((a,b)=>b.flights-a.flights||a.aircraft.localeCompare(b.aircraft));}
function renderKpis(rows){const cc=new Set(rows.map(x=>x.country)).size,tv=rows.reduce((a,b)=>a+b.visits,0),ts=rows.reduce((a,b)=>a+b.total_stay_seconds,0),avg=tv?Math.round(ts/tv):0;document.querySelector('#kpis').innerHTML=`<div class="kpi"><div class="label">造訪國家／地區</div><div class="value">${cc}</div><div class="sub">目前篩選範圍</div></div><div class="kpi"><div class="label">總造訪次數</div><div class="value">${tv}</div><div class="sub">跨境抵達才計次</div></div><div class="kpi"><div class="label">累積停留時間</div><div class="value">${dur(ts).split(' ')[0]}</div><div class="sub">${dur(ts)}</div></div><div class="kpi"><div class="label">平均每次停留</div><div class="value">${dur(avg).split(' ')[0]}</div><div class="sub">${dur(avg)}</div></div>`;}
function renderTable(rows){const all=yearEl.value==='all';document.querySelector('#annualTitle').textContent=all?`${years[0]}–${years.at(-1)} 全期間彙總`:`${yearEl.value} 年度實績`;document.querySelector('#annualPeriodHead').textContent=all?'期間':'年份';document.querySelector('#annualBody').innerHTML=rows.slice().sort((a,b)=>a.country.localeCompare(b.country,'zh-Hant')).map(x=>`<tr class="annual-row ${selectedSummaryCountry===x.country?'selected':''}"><td>${all?`${years[0]}–${years.at(-1)}`:x.year}</td><td><button class="country-link" data-country="${esc(x.country)}">${esc(x.country)}</button></td><td>${x.visits} 次</td><td>${dur(x.avg_interval_seconds)}</td><td>${dur(x.avg_stay_seconds)}</td><td>${dur(x.total_stay_seconds)}</td></tr>`).join('')||'<tr><td colspan="6">沒有符合條件的資料</td></tr>';}
function renderAircraft(rows){document.querySelector('#aircraftTitle').textContent=yearEl.value==='all'?'全期間機型使用實績':`${yearEl.value} 機型使用實績`;document.querySelector('#aircraftCount').textContent=`${rows.length} 種機型`;document.querySelector('#aircraftHint').textContent=selectedAircraft?`已鎖定「${selectedAircraft}」，點擊空白處解除`:'點擊機型可篩選下方所有航班資料';document.querySelector('#aircraftBody').innerHTML=rows.map(x=>`<tr class="aircraft-row ${selectedAircraft===x.aircraft?'selected':''}"><td><button class="aircraft-link" data-aircraft="${esc(x.aircraft)}">${esc(x.aircraft)}</button></td><td>${x.flights} 次</td><td>${dur(x.avg_interval_seconds)}</td><td>${dur(x.avg_flight_seconds)}</td><td>${dur(x.total_flight_seconds)}</td><td>${x.years}</td></tr>`).join('')||'<tr><td colspan="6">沒有符合條件的資料</td></tr>';}
function renderDetails(v){document.querySelector('#detailCount').textContent=`${v.length} 筆${selectedSummaryCountry?` · ${selectedSummaryCountry}`:''}`;document.querySelector('#detailHint').textContent=selectedSummaryCountry?`點擊頁面空白處可解除「${selectedSummaryCountry}」篩選`:'點擊上方年度實績中的國家，可快速篩選此表';document.querySelector('#detailBody').innerHTML=v.slice().sort((a,b)=>b.arrival.localeCompare(a.arrival)).map(x=>`<tr><td>${esc(x.country)}</td><td>${dt(x.arrival)}</td><td>${dt(x.departure)}</td><td>${dur(x.durationSeconds)}</td><td>${esc(x.arrivalFlight)}</td><td>${esc(x.departureFlight)}</td><td>${esc(x.arrivalAirport)}</td><td>${esc(x.departureAirport)}</td></tr>`).join('')||'<tr><td colspan="8">沒有符合條件的資料</td></tr>';}
function renderFlights(f){document.querySelector('#flightCount').textContent=`${f.length} 筆${selectedAircraft?` · ${selectedAircraft}`:''}`;document.querySelector('#flightBody').innerHTML=f.slice().sort((a,b)=>b.departure.localeCompare(a.departure)).map(x=>`<tr class="${x.completed?'':'future-row'}"><td>${x.date}</td><td>${esc(x.flight)}</td><td>${esc(x.from)}</td><td>${esc(x.to)}</td><td>${dt(x.departure)}</td><td>${dt(x.arrival)}</td><td>${esc(x.duration)}</td><td>${esc(x.airline)}</td><td>${esc(x.aircraft)}</td><td>${esc(x.registration)||'—'}</td><td>${esc(x.seatNumber)||'—'}</td><td>${x.completed?'已完成':'未出發'}</td></tr>`).join('')||'<tr><td colspan="12">沒有符合條件的資料</td></tr>';}
function chart(id,rows,key,fmt){let grouped;if(yearEl.value==='all')grouped=years.map(year=>({year,value:D.annual.filter(x=>x.year===year&&(countryEl.value==='all'||x.country===countryEl.value)).reduce((a,b)=>a+b[key],0)})).filter(x=>x.value>0);else grouped=[{year:Number(yearEl.value),value:rows.reduce((a,b)=>a+b[key],0)}];const max=Math.max(...grouped.map(x=>x.value),1);document.querySelector(id).innerHTML=grouped.map(x=>`<div class="bar-group"><div class="bar" style="height:${Math.max(4,x.value/max*220)}px"><span>${fmt(x.value)}</span></div><div class="xlab">${x.year}</div></div>`).join('')||'<p>沒有資料</p>';}
function render(){const r=filteredAnnual();renderKpis(r);renderTable(r);renderAircraft(aircraftSummary());renderDetails(filteredVisits());renderFlights(filteredFlights());chart('#visitChart',r,'visits',v=>v+'次');chart('#stayChart',r,'total_stay_seconds',v=>Math.round(v/86400)+'天');}
function clearSelections(){if(!selectedSummaryCountry&&!selectedAircraft)return;selectedSummaryCountry=null;selectedAircraft=null;render();}
yearEl.addEventListener('change',()=>{selectedSummaryCountry=null;selectedAircraft=null;render()});countryEl.addEventListener('change',()=>{selectedSummaryCountry=null;selectedAircraft=null;render()});document.querySelector('#resetBtn').addEventListener('click',()=>{yearEl.value='all';countryEl.value='all';selectedSummaryCountry=null;selectedAircraft=null;render()});
document.querySelector('#annualBody').addEventListener('click',e=>{const b=e.target.closest('.country-link');if(!b)return;e.stopPropagation();selectedSummaryCountry=selectedSummaryCountry===b.dataset.country?null:b.dataset.country;renderTable(filteredAnnual());renderDetails(filteredVisits());document.querySelector('#detailsCard').scrollIntoView({behavior:'smooth',block:'start'})});
document.querySelector('#aircraftBody').addEventListener('click',e=>{const b=e.target.closest('.aircraft-link');if(!b)return;e.stopPropagation();selectedAircraft=selectedAircraft===b.dataset.aircraft?null:b.dataset.aircraft;renderAircraft(aircraftSummary());renderFlights(filteredFlights());document.querySelector('#flightsCard').scrollIntoView({behavior:'smooth',block:'start'})});
['#annualTableCard','#aircraftTableCard','#detailsCard','#flightsCard'].forEach(s=>document.querySelector(s).addEventListener('click',e=>e.stopPropagation()));document.addEventListener('click',clearSelections);
document.querySelector('#downloadCsv').addEventListener('click',()=>{const rows=filteredAnnual(),all=yearEl.value==='all';const csv=['期間,國家／地區,造訪次數,平均到訪間隔,平均每次停留,總停留',...rows.map(x=>[all?`${years[0]}-${years.at(-1)}`:x.year,x.country,x.visits,dur(x.avg_interval_seconds),dur(x.avg_stay_seconds),dur(x.total_stay_seconds)].join(','))].join('\n');const b=new Blob(['﻿'+csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='flight-summary.csv';a.click();URL.revokeObjectURL(a.href)});
document.querySelector('#excluded').innerHTML=`<div class="excluded">已排除 ${D.excludedFlights.length} 筆尚未出發航班：${D.excludedFlights.map(x=>`${x.date} ${x.flight}`).join('、')}</div>`;render();
